name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  test:
    name: Environment test
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: action/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install, build and test
        run: |
          npm install
          npm run
          npm test
        env:
          DB_HOST: ${{ secrets.DB_HOST}}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET}}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN}}
